spring:
  application:
    name: sboot-aws-soap-demo
    description: API Rest de consulta ao SOAP Demo
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  beaninfo:
    ignore: true
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
  error:
    whitelabel:
      enabled: false
management:
  server:
    port: 9090
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

---

# configurações para desenvolvimento local

spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

demo:
  ws:
    serviceUrl: https://www.crcind.com:443/csp/samples/SOAP.Demo.cls


