spring:
  application:
    name: sboot-consulta-cep
    description: Serviço de Consultar CEP
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  beaninfo:
    ignore: true
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
  error:
    whitelabel:
      enabled: false
management:
  server:
    port: 9090
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

---

# configurações para desenvolvimento local

spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

demo:
  ws:
    serviceUrl: https://www.crcind.com:443/csp/samples/SOAP.Demo.cls



---

# configurações para ambientes e testes integrados
spring:
  profiles: des,qa,uat,prd
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

demo:
  ws:
    serviceAddInteger: http://tempuri.org/SOAP.Demo.AddInteger
    serviceDivideInteger: http://tempuri.org/SOAP.Demo.DivideInteger
    serviceFindPerson: http://tempuri.org/SOAP.Demo.FindPerson
    serviceGetByName: http://tempuri.org/SOAP.Demo.GetByName
    serviceGetDataSetByName: http://tempuri.org/SOAP.Demo.GetDataSetByName
    serviceGetListByName: http://tempuri.org/SOAP.Demo.GetListByName
    serviceLookupCity: http://tempuri.org/SOAP.Demo.LookupCity
    serviceMission: http://tempuri.org/SOAP.Demo.Mission
    serviceQueryByName: http://tempuri.org/SOAP.Demo.QueryByName

